import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import '../vendor/normalize.css'
import './globals.css'
import styles from './layout.module.scss'
import Left from '../images/body/Vector_45.svg'
import Center from '../images/body/Vector_46.svg'
import Right from '../images/body/Vector_47.svg'

const notoSans = Noto_Sans({ subsets: ['cyrillic'], display: 'swap' })

const centuryGothic = localFont({
  src: '../vendor/fonts/CenturyGothic-Bold.woff',
  display: 'swap',
  weight: '700',
  style: 'normal',
  variable: '--font-century-gothic',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="ru"
      className={`${centuryGothic.variable} ${notoSans.className}`}
    >
      <body className={styles.body}>
        <div className={styles.body_decor_wrapper}>
          <Left className={`${styles.decor} ${styles.decor_left}`} />
          <Center className={`${styles.decor} ${styles.decor_center}`} />
          <Right className={`${styles.decor} ${styles.decor_right}`} />
        </div>
        {children}
      </body>
    </html>
  )
}
